version: '3.8'

services:
  hugo-nginx:
    # image: 982534381318.dkr.ecr.ap-southeast-1.amazonaws.com/portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    container_name: hugo_nginx_site
