name: CI/CD to ECR and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: build-and-push     
    name: Pull image from ECR & deploy with Docker Compose
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull image and start service
        run: |
          sudo docker compose down || true
          sudo docker system prune -af
          sudo docker compose up -d --build

      - name: Show running containers
        run: sudo docker ps

